#include "../transitionObject.cpp"
#include "../animationObject.cpp"
#include "./ledMapping.cpp"
#include "./settings.cpp"
#include "./nonAddressableLed/nonAddressableController.cpp"
#include "./addressableLedDevice.cpp"
#include "./nonAddressableLed/nonAddressableLedDevice.cpp"